#ifndef _DRIVER_H
#define _DRIVER_H

typedef enum {
	DRIVER_STATUS_OK = 0,
	DRIVER_STATUS_ERROR,
	DRIVER_STATUS_NOT_IMPLEMENTED,
	DRIVER_STATUS_INVALID_PARAM,
	DRIVER_STATUS_DEVICE_NOT_FOUND
} driver_status_t;

#endif // _DRIVER_H
